image: Visual Studio 2017
platform: Win32
configuration: Release

version: "{build}"

install:
  - python --version
  - pip install PySide pyinstaller

build_script:
  - pyi-makespec -F run.py
  - pyinstaller run.spec

artifacts:
  - path: 'dist\run.exe'

deploy:
  release: auction67-v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: 83v5Rb8DnAangj1Sa4eHj9EbazexsQSvA018dHo9cLI1i5JWKbhdkcnRHPmcxLnC
  artifact: dist\run.exe
  draft: false
  prerelease: false
  on:
    branch: master