image: Visual Studio 2017
platform: Win32
configuration: Release

version: "{build}"

install:
  - python --version
  - pip install PySide pyinstaller

build_script:
  - pyinstaller run.py

artifacts:
  - path: 'build\run\*'
  - path: C:\Windows\System\python27.dll