image: Visual Studio 2017
platform: Win32
configuration: Release

version: "{build}"

install:
  - python --version
  - pip install -U PySide pyinstaller

build_script:
  - pyinstaller run.py

artifacts:
  - path: build\run\run.exe