image: Visual Studio 2017
platform: Win32
configuration: Release

version: "{build}"

install:
  - python --version
  - pip install -U PySide
  - pip install pyinstaller

build_script:
  - pyinstaller run.py

artifacts:
  - path: run.exe