image: Visual Studio 2017
platform: Win32
configuration: Release

version: "{build}"

install:
  - python --version
  - pip install PySide pyinstaller

build_script:
  - pyinstaller --onefile run.py

artifacts:
  - path: 'build\run\*'