image: Visual Studio 2017
platform: Win32
configuration: Release

version: "{build}"

install:
  - python --version
  - pip install PySide pyinstaller

build_script:
  - pyi-makespec -F run.py
  - pyinstaller -n auction67 run.spec

artifacts:
  - path: 'dist\run.exe'
