image: Visual Studio 2017
platform: Win32
configuration: Release

version: "{build}"

install:
  - python --version
  - pip install PySide pyinstaller

build_script:
  - pyinstaller run.py
  - copy C:\Windows\system32\python27.dll build\run\

artifacts:
  - path: 'build\run\*'